/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import java.awt.event.ActionEvent;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import org.apache.log4j.Logger;
import rmiCommunication.RMIServer;
import socketCommunication.threads.ServerThread;

/**
 *
 * @author veljko
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    private ServerThread serverThread;
    private final Logger LOGGER = Logger.getLogger(FrmMain.class);
    private static Registry registry;

    public FrmMain() {
        initComponents();
        initListeners();
        jMenuItemStop.setEnabled(false);
        jMenuItemRMIStop.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuServer = new javax.swing.JMenu();
        jMenuItemStart = new javax.swing.JMenuItem();
        jMenuItemStop = new javax.swing.JMenuItem();
        jMenuRMIServer = new javax.swing.JMenu();
        jMenuItemRMIStart = new javax.swing.JMenuItem();
        jMenuItemRMIStop = new javax.swing.JMenuItem();
        JMenuConfiguartion = new javax.swing.JMenu();
        jMenuItemDatabaseConfiguartion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuServer.setText("Socket Server");

        jMenuItemStart.setText("Start");
        jMenuServer.add(jMenuItemStart);

        jMenuItemStop.setText("Stop");
        jMenuServer.add(jMenuItemStop);

        jMenuBar.add(jMenuServer);

        jMenuRMIServer.setText("RMI Server");

        jMenuItemRMIStart.setText("Start");
        jMenuRMIServer.add(jMenuItemRMIStart);

        jMenuItemRMIStop.setText("Stop");
        jMenuRMIServer.add(jMenuItemRMIStop);

        jMenuBar.add(jMenuRMIServer);

        JMenuConfiguartion.setText("Configuration");

        jMenuItemDatabaseConfiguartion.setText("Database");
        JMenuConfiguartion.add(jMenuItemDatabaseConfiguartion);

        jMenuBar.add(JMenuConfiguartion);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuConfiguartion;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemDatabaseConfiguartion;
    private javax.swing.JMenuItem jMenuItemRMIStart;
    private javax.swing.JMenuItem jMenuItemRMIStop;
    private javax.swing.JMenuItem jMenuItemStart;
    private javax.swing.JMenuItem jMenuItemStop;
    private javax.swing.JMenu jMenuRMIServer;
    private javax.swing.JMenu jMenuServer;
    // End of variables declaration//GEN-END:variables

    private void initListeners() {
        jMenuItemStart.addActionListener((ActionEvent e) -> {
            if (serverThread == null || !serverThread.isAlive()) {
                serverThread = new ServerThread();
                serverThread.start();

                jMenuItemStart.setEnabled(false);
                jMenuItemStop.setEnabled(true);
            }
        });

        jMenuItemStop.addActionListener((ActionEvent e) -> {
            if (serverThread.getServerSocket() != null && !serverThread.getServerSocket().isClosed()) {
                try {
                    serverThread.getServerSocket().close();

                    jMenuItemStart.setEnabled(true);
                    jMenuItemStop.setEnabled(false);
                } catch (IOException ex) {
                    LOGGER.error(ex.getMessage());
                }
            }
        });

        jMenuItemDatabaseConfiguartion.addActionListener((ActionEvent e) -> {
            new FrmDatabaseConfiguration().setVisible(true);
        });

        jMenuItemRMIStart.addActionListener((ActionEvent e) -> {
            try {
                registry = getRegistry();
                registry.rebind("Server", new RMIServer());
                LOGGER.info("RMI server created");

                jMenuItemRMIStop.setEnabled(true);
                jMenuItemRMIStart.setEnabled(false);
            } catch (RemoteException ex) {
                LOGGER.error(ex);
            }
        });

        jMenuItemRMIStop.addActionListener((ActionEvent e) -> {
            try {
                registry.unbind("Server");
                jMenuItemRMIStop.setEnabled(false);
                jMenuItemRMIStart.setEnabled(true);
            } catch (RemoteException | NotBoundException ex) {
                LOGGER.error(ex);
            }
        });

    }

    public static Registry getRegistry() throws RemoteException {
        if (registry == null) {
            registry = LocateRegistry.createRegistry(1099);
        }
        return registry;
    }

    public FrmMain getFrm() {
        return this;
    }

}
